### PR TITLE
Load angry levels with AbruptLevelChanger 

### PR DESCRIPTION
**Pull request by Hydraxous**
Allows AbruptLevelChanger to load angry levels by id.

Also im not sure why the FinalRank file looks like the whole file was replaced, it might be formatting or something im not sure.
The patch for FinalRank.ChangeLevel was the only thing actually changed in that file.

### CODE REVIEW

**Comment by eternalUnion** [comment]
There also seems to be an ancient method called `GetLevel` in Plugin.cs which I rarely used

```cs
public static LevelContainer GetLevel(string id)
{
	foreach (AngryBundleContainer container in angryBundles.Values)
	{
		foreach (LevelContainer level in container.levels.Values)
		{
			if (level.field.data.uniqueIdentifier == id)
				return level;
		}
	}

	return null;
}
```

yeah no idea why I did not make that sort of method

**Comment by Hydraxous** [comment]
ooooh I didnt even see that

**Comment by eternalUnion** [comment]
epic fail
```cs
public static bool TryFindLevel(string id, out LevelContainer level)
{
    level = null;

    foreach (AngryBundleContainer container in Plugin.angryBundles.Values)
    {
        foreach (LevelContainer levelContainer in container.levels.Values)
        {
            if (level.data.uniqueIdentifier == id) // not level, levelContainer
            {
                level = levelContainer;
                return true;
            }
        }
    }

    return false;
}
```

**Comment by Hydraxous** [comment]
I'm sorry.

**Pull request merged**
